GET http://localhost:5000/games/2020

###

PUT http://localhost:5000/games/5f8ab605dea6f84aba92294b/5f8814281f398f2338bdaebf
Content-Type: application/json

{
"goals": 7,
"assists": 7,
"penalties": 7
}
