GET https://hasses-sega-gubbar.herokuapp.com/games/2020
###

GET https://hasses-sega-gubbar.herokuapp.com/games/results

###

POST https://hasses-sega-gubbar.herokuapp.com/games/5f8ab6bbdea6f84aba92294c/5f99c46ddb7ced2d2435c1f6
Content-Type: application/json

{ 
"goals": 2,
"assists": 3,
"penalties": 14
}

###

PUT https://hasses-sega-gubbar.herokuapp.com/games/5f995f8cd463033f20093b87
Content-Type: application/json

{
"goals": 9,
"assists": 9,
"penalties": 9
}

###

DELETE https://hasses-sega-gubbar.herokuapp.com/games/5f995f8cd463033f20093b87
###
