GET http://localhost:5000/games/2020
###

GET http://localhost:5000/games/results

###

POST http://localhost:5000/games/5f8ab6bbdea6f84aba92294c/5f99c46ddb7ced2d2435c1f6
Content-Type: application/json

{ 
"goals": 2,
"assists": 3,
"penalties": 14
}

###

PUT http://localhost:5000/games/5f995f8cd463033f20093b87
Content-Type: application/json

{
"goals": 9,
"assists": 9,
"penalties": 9
}

###

DELETE http://localhost:5000/games/5f995f8cd463033f20093b87
###
