POST https://hasses-sega-gubbar.herokuapp.com/users/register
Content-Type: application/json

{
"username": "Enga",
"password": "12345",
"name": "Johan Engström"
}

###

POST https://hasses-sega-gubbar.herokuapp.com/users/login
Content-Type: application/json

{
    "username": "NThelin",
    "password": "Minora0805"
}

###